"""
VerifiMind-PEAS Privacy Policy — v1.0
Z-Protocol v1.1 compliant: data minimization, explicit consent, right to erasure.
GDPR / PDPA aligned.
"""

PRIVACY_POLICY_VERSION = "1.0"
PRIVACY_POLICY_EFFECTIVE_DATE = "2026-03-18"

PRIVACY_POLICY = """
VerifiMind-PEAS — Privacy Policy v1.0
Effective: March 18, 2026

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

WHO WE ARE
VerifiMind-PEAS is an open-source multi-model AI validation framework created
by Alton Lee (Human Orchestrator, YSenseAI). This Privacy Policy applies to
the Early Adopter (EA) registration program at verifimind.ysenseai.org.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

WHAT WE COLLECT
When you register as an Early Adopter, we collect:

  ✓ Email address (required) — to identify your EA account and communicate
    product updates if you opt in
  ✓ Name (optional) — display purposes only, never shared or published
    without your explicit consent
  ✓ Your UUID (generated by us) — your pseudonymous EA identifier
  ✓ Registration timestamp — when you joined the EA program
  ✓ Consent records — that you accepted T&C and this Privacy Policy,
    and when
  ✓ Feedback message (optional) — what you shared at registration to
    help us understand your needs

WHAT WE DO NOT COLLECT
  ✗ Passwords or credentials
  ✗ Payment information (no billing in the current beta period)
  ✗ Your IP address linked to your email (anonymous usage telemetry
    exists separately and is never connected to EA records)
  ✗ Location or device information
  ✗ Browsing behaviour or tracking cookies
  ✗ Any data beyond what you voluntarily provide

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

WHY WE COLLECT IT
  • To grant you Early Adopter benefits (3 months free v0.6.0-Beta access)
  • To communicate product updates, if you opted in to updates
  • To improve VerifiMind-PEAS based on aggregate, anonymised feedback
  • To maintain a compliance record that you gave informed consent

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

HOW LONG WE KEEP YOUR DATA
  • EA records: for the duration of your EA membership + 90 days
  • Feedback messages: kept indefinitely in anonymised form after 6 months
  • On deletion request: all personal data purged within 7 business days

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

YOUR RIGHTS
You have the right to:

  • Access your data — GET /early-adopters/status/{your-uuid}
  • Delete your data — POST /early-adopters/optout/{your-uuid}
    (marks your record for deletion; purged within 7 days)
  • Correct your data — raise a GitHub Discussion or contact us
  • Withdraw consent at any time — same opt-out endpoint

These rights are free of charge and will be actioned promptly.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DATA SHARING
We do NOT sell, rent, or share your personal data with any third party,
except:

  • Google Cloud Platform — hosting infrastructure and Firestore database
    storage. GCP is bound by its own Privacy Policy and GDPR commitments.
    No other third parties receive your data.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SECURITY
Your EA record is stored in Google Cloud Firestore with restricted access.
We do not log your email address in server logs. Your UUID is your primary
identifier in all internal systems.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CONTACT
For privacy questions or data requests:
  GitHub Discussions: github.com/creator35lwb-web/VerifiMind-PEAS/discussions
  Or use the opt-out endpoint for immediate data deletion.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This policy aligns with GDPR (EU), PDPA (Singapore/ASEAN), and the
Z-Protocol v1.1 ethical framework (data minimisation, transparency,
user autonomy).

VerifiMind-PEAS is open source: github.com/creator35lwb-web/VerifiMind-PEAS
"""
