name: Bug Report
description: Report a bug or unexpected behavior in VerifiMind-PEAS
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill out the information below to help us investigate.
        **Security vulnerabilities should NOT be reported here.** Please use our [Security Policy](https://github.com/creator35lwb-web/VerifiMind-PEAS/security/policy).

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Configure the MCP server with...
        2. Send a request to...
        3. Observe the error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: VerifiMind-PEAS Version
      description: Which version are you using?
      placeholder: e.g., v0.4.0
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - MCP Server
        - X Agent (Innovator)
        - Z Agent (Guardian)
        - CS Agent (Validator)
        - Synthesis Engine
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details.
      placeholder: |
        - OS: Ubuntu 22.04
        - Python: 3.11
        - MCP Client: Claude Desktop
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Any relevant log output (please redact sensitive information).
      render: shell
    validations:
      required: false
