"""
Handoff Formatter — v0.5.11 Coordination Foundation
=====================================================

Generates MACP v2.2 compliant markdown handoff documents from structured data.
Follows the format defined in .macp/protocol.md §4.1.

Output is a human-readable markdown file suitable for saving to:
  .macp/handoffs/YYYYMMDD_AGENTID_DESCRIPTION.md
"""

from datetime import datetime, timezone


def format_handoff_markdown(record: dict) -> str:
    """Render a handoff record dict as MACP v2.2 markdown.

    Args:
        record: Handoff dict as produced by build_handoff_record().

    Returns:
        Formatted markdown string ready to save as a .md file.
    """
    agent_id = record.get("agent_id", "unknown")
    session_type = record.get("session_type", "session")
    timestamp = record.get("timestamp", datetime.now(timezone.utc).isoformat())
    handoff_id = record.get("handoff_id", "")
    status = record.get("status", "CREATED")
    next_agent = record.get("next_agent", "")

    completed = record.get("completed", [])
    decisions = record.get("decisions", [])
    artifacts = record.get("artifacts", [])
    pending = record.get("pending", [])
    blockers = record.get("blockers", [])

    def bullet_list(items: list[str]) -> str:
        if not items:
            return "- (none)\n"
        return "".join(f"- {item}\n" for item in items)

    lines = [
        f"# Session Handoff: {timestamp[:10]}",
        "",
        f"## Agent: {agent_id}",
        f"## Session Type: {session_type}",
        f"## Status: {status}",
        f"## Handoff ID: {handoff_id}",
        f"## MACP Version: 2.2 \"Identity\"",
        "",
        "---",
        "",
        "### Completed",
        bullet_list(completed),
        "### Decisions Made",
        bullet_list(decisions),
        "### Artifacts Created",
        bullet_list(artifacts),
        "### Pending for Next Agent",
        bullet_list(pending),
        "### Blockers",
        bullet_list(blockers) if blockers else "- (none)\n",
        f"### Recommended Next Agent: {next_agent or '(unspecified)'}",
        "",
        "---",
        "",
        f"*MACP v2.2 \"Identity\" — Generated by VerifiMind-PEAS Coordination Layer v0.5.11*",
        f"*Timestamp: {timestamp}*",
    ]

    return "\n".join(lines)


def parse_handoff_filename(filename: str) -> dict:
    """Parse a MACP handoff filename into its components.

    Expected format: YYYYMMDD_AGENTID_DESCRIPTION.md

    Args:
        filename: Filename string (with or without .md extension).

    Returns:
        Dict with keys: date, agent_id, description (or empty strings on failure).
    """
    name = filename.removesuffix(".md")
    parts = name.split("_", 2)
    if len(parts) == 3:
        return {"date": parts[0], "agent_id": parts[1], "description": parts[2]}
    if len(parts) == 2:
        return {"date": parts[0], "agent_id": parts[1], "description": ""}
    return {"date": "", "agent_id": "", "description": name}
