import os
from datetime import datetime
from fpdf import FPDF
from typing import Dict, Any, List
from src.core.logging_config import get_logger

logger = get_logger(__name__)

class VerifiMindPDF(FPDF):
    """Custom PDF class for VerifiMind branding and layout."""
    
    def header(self):
        # Logo placeholder or Brand Name
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(100, 100, 100) # Grey
        self.cell(0, 10, 'VerifiMind™ PEAS - Genesis Validation Report', 0, 1, 'R')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by VerifiMind X-Z-CS Trinity', 0, 0, 'C')

class ValidationReportGenerator:
    """
    Generates the 'publication-ready' PDF report synthesizing 
    Agent insights and Socratic Scrutiny.
    """

    def __init__(self, output_dir: str):
        self.output_dir = output_dir
        self.pdf = VerifiMindPDF()
        self.pdf.set_auto_page_break(auto=True, margin=15)

    def generate(self, app_spec: Any, agent_results: Dict[str, Any], socratic_data: Dict) -> str:
        """
        Main driver to build the full PDF report.
        """
        logger.info(f"Generating PDF report for {app_spec.app_name}...")
        
        self.pdf.add_page()
        
        # 1. Title Page
        self._create_title_page(app_spec)
        
        # 2. Executive Summary (The Trinity Verdict)
        self._add_section_title("1. Executive Summary: The Trinity Verdict")
        self._add_trinity_matrix(agent_results)
        
        # 3. Socratic Concept Scrutiny (The Deep Dive)
        self._add_section_title("2. Socratic Concept Scrutiny")
        self._add_socratic_deep_dive(socratic_data)
        
        # 4. Strategic Roadmap
        self._add_section_title("3. Strategic Roadmap")
        self._add_roadmap(socratic_data.get('step_4_strategy', {}))

        # 5. IP & Blockchain Proof
        self._add_section_title("4. IP & Attribution Proof")
        self._add_ip_proof(app_spec)

        # Save
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{app_spec.app_name.replace(' ', '_')}_Validation_Report_{timestamp}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        
        # Ensure dir exists
        os.makedirs(self.output_dir, exist_ok=True)
        
        self.pdf.output(filepath)
        logger.info(f"PDF Report saved to: {filepath}")
        return filepath

    def _create_title_page(self, app_spec):
        self.pdf.ln(40)
        self.pdf.set_font('Helvetica', 'B', 24)
        self.pdf.set_text_color(0, 51, 102) # Dark Blue
        self.pdf.multi_cell(0, 10, app_spec.app_name, 0, 'C')
        
        self.pdf.ln(10)
        self.pdf.set_font('Helvetica', '', 14)
        self.pdf.set_text_color(0)
        self.pdf.cell(0, 10, "Genesis Validation Report", 0, 1, 'C')
        
        self.pdf.ln(5)
        self.pdf.set_font('Helvetica', 'I', 12)
        self.pdf.cell(0, 10, f"Category: {app_spec.category}", 0, 1, 'C')
        
        self.pdf.ln(30)
        self.pdf.set_font('Courier', '', 10)
        self.pdf.multi_cell(0, 5, f"Description:\n{app_spec.description[:300]}...", 0, 'C')
        
        self.pdf.ln(40)
        self.pdf.set_font('Helvetica', 'B', 12)
        self.pdf.cell(0, 10, f"Date: {datetime.now().strftime('%B %d, %Y')}", 0, 1, 'C')
        self.pdf.add_page()

    def _add_section_title(self, title):
        self.pdf.set_font('Helvetica', 'B', 16)
        self.pdf.set_text_color(0, 51, 102)
        self.pdf.cell(0, 10, title, 0, 1, 'L')
        self.pdf.line(10, self.pdf.get_y(), 200, self.pdf.get_y())
        self.pdf.ln(5)

    def _add_trinity_matrix(self, results):
        self.pdf.set_font('Helvetica', '', 11)
        self.pdf.set_text_color(0)
        
        # X Agent
        x = results.get('X')
        self.pdf.set_font('Helvetica', 'B', 12)
        self.pdf.cell(0, 10, "X Intelligent (Innovation Engine)", 0, 1)
        self.pdf.set_font('Helvetica', '', 11)
        self.pdf.multi_cell(0, 6, f"Status: {x.status.upper()} | Score: {getattr(x, 'risk_score', 'N/A')}/100\nAnalysis: {x.analysis[:300]}...")
        self.pdf.ln(5)
        
        # Z Agent
        z = results.get('Z')
        self.pdf.set_font('Helvetica', 'B', 12)
        self.pdf.cell(0, 10, "Z Guardian (Ethics & Compliance)", 0, 1)
        self.pdf.set_font('Helvetica', '', 11)
        self.pdf.multi_cell(0, 6, f"Status: {z.status.upper()} | Score: {getattr(z, 'risk_score', 'N/A')}/100\nAnalysis: {z.analysis[:300]}...")
        self.pdf.ln(5)

        # CS Agent
        cs = results.get('CS')
        self.pdf.set_font('Helvetica', 'B', 12)
        self.pdf.cell(0, 10, "CS Security (Vulnerability Scan)", 0, 1)
        self.pdf.set_font('Helvetica', '', 11)
        self.pdf.multi_cell(0, 6, f"Status: {cs.status.upper()} | Score: {getattr(cs, 'validation_score', 'N/A')}/100\nVerdict: {getattr(cs, 'verdict', 'N/A')}")
        self.pdf.ln(10)

    def _add_socratic_deep_dive(self, data):
        if not data:
            return
            
        self.pdf.set_font('Helvetica', 'B', 12)
        self.pdf.cell(0, 10, "Step 1: Clarification & Assumptions", 0, 1)
        self.pdf.set_font('Helvetica', '', 11)
        self.pdf.multi_cell(0, 6, str(data.get('step_1_clarification', 'N/A')))
        self.pdf.ln(5)

        self.pdf.set_font('Helvetica', 'B', 12)
        self.pdf.cell(0, 10, "Step 2: Feasibility Analysis", 0, 1)
        self.pdf.set_font('Courier', '', 10)
        feasibility = data.get('step_2_feasibility', {})
        for k, v in feasibility.items():
            if 'score' in k:
                self.pdf.cell(0, 6, f"- {k.replace('_', ' ').title()}: {v}", 0, 1)
        self.pdf.ln(5)

        self.pdf.set_font('Helvetica', 'B', 12)
        self.pdf.set_text_color(150, 0, 0) # Dark Red for Challenges
        self.pdf.cell(0, 10, "Step 3: Socratic Challenges (Devil's Advocate)", 0, 1)
        self.pdf.set_text_color(0)
        self.pdf.set_font('Helvetica', 'I', 11)
        challenges = data.get('step_3_challenges', [])
        for challenge in challenges:
            self.pdf.multi_cell(0, 6, f"Q: {challenge}")
            self.pdf.ln(2)
        self.pdf.ln(5)

    def _add_roadmap(self, strategy):
        self.pdf.set_font('Helvetica', '', 11)
        verdict = strategy.get('verdict', 'N/A')
        self.pdf.cell(0, 10, f"Strategic Verdict: {verdict}", 0, 1)
        
        milestones = strategy.get('roadmap_milestones', [])
        self.pdf.ln(5)
        for ms in milestones:
             self.pdf.cell(0, 6, f"[ ] {ms}", 0, 1)
        self.pdf.ln(10)

    def _add_ip_proof(self, app_spec):
        self.pdf.set_font('Courier', '', 10)
        self.pdf.multi_cell(0, 5, 
            f"App ID: {app_spec.app_id}\n"
            f"Timestamp: {datetime.utcnow().isoformat()}\n"
            f"Methodology: Genesis Prompt Engineering v2.0\n"
            f"Generated by: VerifiMind PEAS System\n"
            f"License: Proprietary / Creator Owned\n"
            "Blockchain Status: Pending Minting (Polygon)"
        )